Server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.87:3306/foodka_db?serverTimezone=UTC
      username: root
      password: why200101
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/    # 图片上传后返回的页面的前缀
    suffix: .html   # 后缀

SavePath:
   ProfilePhoto: '\Users\liuxiaolin\Desktop\Java\Springbot\pic\' # 图标存储路径
   ProfilePhotoMapper: '/pic/'                                  # 图标映射路径


mybatis-plus:
  global-config:
    db-config:
      id-type: auto

